kind: ConfigMap
apiVersion: v1
metadata:
  name: admin
data:
  application.yml: |-
    spring:
     cloud:
      kubernetes:
        discovery:
          service-labels:
            spring-boot: true
          #enable if your admin is deployed in the different namespace then microservices 
          #all-namespaces: true